name: README Update Automation

on:
  pull_request:
    types: [opened]

jobs:
  update-readme:
    name: Update README after PR merge
    runs-on: ubuntu-latest

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python using the latest stable version
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11.9'

      # Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Extract PR Number and Commit SHA from the GitHub event context
      - name: Extract PR Number and Commit SHA
        id: extract_info
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMIT_SHA=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Generate Updated README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_ACTIONS_TOKEN: ${{ github.token }}
          LANGCHAIN_TRACING_V2: true
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
          LANGCHAIN_PROJECT: "test-ai-check"
          REPO_PATH: ${{ github.repository }}

      # Run the Python script
        run: | 
          python main.py

      # Additional step to enable debugging, helps in troublshooting
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          
